# Generated by Django 4.1.4 on 2023-01-16 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventhost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostimages',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_hosts', to='eventhost.eventhost'),
        ),
    ]
