# Generated by Django 4.1.4 on 2023-01-16 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventhost', '0002_alter_hostimages_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventhost',
            old_name='host_name',
            new_name='management_name',
        ),
    ]
