# Generated by Django 4.1.4 on 2023-01-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventhost', '0003_rename_host_name_eventhost_management_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventhost',
            old_name='management_name',
            new_name='host_name',
        ),
    ]
