# Generated by Django 4.1.4 on 2023-01-16 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_host'),
        ('eventhost', '0004_rename_management_name_eventhost_host_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventhost',
            old_name='host_name',
            new_name='management_name',
        ),
        migrations.AddField(
            model_name='eventhost',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.host'),
            preserve_default=False,
        ),
    ]
