# Generated by Django 4.1.4 on 2023-01-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventhost', '0006_eventcustomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcustomer',
            name='date',
        ),
    ]
