# Generated by Django 4.1.4 on 2023-01-17 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventhost', '0007_remove_eventcustomer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcustomer',
            name='managingfirm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managingfirm', to='eventhost.eventhost'),
        ),
        migrations.AlterField(
            model_name='eventcustomer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventcustomers', to=settings.AUTH_USER_MODEL),
        ),
    ]
