# Generated by Django 4.1.4 on 2023-01-17 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventhost', '0009_rename_user_eventcustomer_eventcustomers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventcustomer',
            old_name='eventcustomers',
            new_name='customers',
        ),
    ]
