# Generated by Django 4.1.4 on 2023-01-17 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventhost', '0010_rename_eventcustomers_eventcustomer_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcustomer',
            name='customers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL),
        ),
    ]
