# Generated by Django 4.1.4 on 2023-01-20 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventhost', '0014_alter_messages_host'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
