# Generated by Django 4.1.4 on 2023-01-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhost', '0015_delete_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventhost',
            name='image',
            field=models.ImageField(default='defaulthost.jpg', upload_to='hostImages'),
        ),
        migrations.DeleteModel(
            name='HostImages',
        ),
    ]
