# Generated by Django 4.1.4 on 2023-01-21 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventhost', '0017_remove_eventhost_location_eventhost_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventhost',
            name='description',
        ),
        migrations.RemoveField(
            model_name='eventhost',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='eventhost',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='eventhost',
            name='state',
        ),
    ]
