# Generated by Django 4.1.4 on 2023-01-21 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventhost', '0019_eventhost_city_eventhost_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('eventhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventhost.eventhost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
