# Generated by Django 4.1.4 on 2023-01-22 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhost', '0021_alter_hostfeedback_eventhost'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostfeedback',
            name='stars',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
