# Generated by Django 4.1.4 on 2023-01-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='defaultProfile.jpeg', upload_to='profile_pics'),
        ),
    ]
