# Generated by Django 4.1.4 on 2023-01-07 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_events_options_alter_rating_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.events'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
