# Generated by Django 4.1.4 on 2023-01-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_rating_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='image2',
            field=models.ImageField(default='default.jpeg', upload_to='eventpic'),
        ),
        migrations.AddField(
            model_name='events',
            name='image3',
            field=models.ImageField(default='default.jpeg', upload_to='eventpic'),
        ),
        migrations.AddField(
            model_name='events',
            name='image4',
            field=models.ImageField(default='default.jpeg', upload_to='eventpic'),
        ),
        migrations.AddField(
            model_name='events',
            name='image5',
            field=models.ImageField(default='default.jpeg', upload_to='eventpic'),
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='eventpic'),
        ),
    ]
