# Generated by Django 4.1.4 on 2023-01-11 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_events_image2_events_image3_events_image4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='phonenumber',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')]),
        ),
    ]
