# Generated by Django 4.1.4 on 2023-01-11 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_profile_bio_profile_location_profile_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phonenumber',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
