# Generated by Django 4.1.4 on 2023-01-11 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_profile_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phonenumber',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
