# Generated by Django 4.1.4 on 2023-01-11 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_profile_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
