# Generated by Django 4.1.4 on 2023-01-17 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventhost', '0005_rename_host_name_eventhost_management_name_and_more'),
        ('app', '0026_events_organisers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='organisers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisers', to='eventhost.eventhost'),
        ),
    ]
