# Generated by Django 4.1.4 on 2023-01-17 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventhost', '0012_delete_eventcustomer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0027_alter_events_organisers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='name',
            new_name='function_name',
        ),
        migrations.RemoveField(
            model_name='events',
            name='organisers',
        ),
        migrations.AddField(
            model_name='events',
            name='contact',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='email',
            field=models.EmailField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='managingfirm',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='managingfirm', to='eventhost.eventhost'),
            preserve_default=False,
        ),
    ]
