# Generated by Django 4.1.4 on 2023-01-17 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_rename_name_events_function_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='customer',
            new_name='customers',
        ),
    ]
