# Generated by Django 4.1.4 on 2023-02-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_mission_workingmodel_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='mission',
        ),
        migrations.AddField(
            model_name='article',
            name='mission',
            field=models.ManyToManyField(to='app.mission'),
        ),
    ]
