# Generated by Django 4.1.4 on 2023-02-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_remove_article_mission_article_mission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='workingmodel',
        ),
        migrations.AddField(
            model_name='article',
            name='workingmodel',
            field=models.ManyToManyField(to='app.workingmodel'),
        ),
    ]
