# Generated by Django 4.1.4 on 2023-02-09 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_article_workingmodel_article_workingmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='mission',
        ),
        migrations.AddField(
            model_name='article',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.mission'),
        ),
    ]
