# Generated by Django 4.1.4 on 2023-02-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_remove_article_mission_article_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(default='eventdefault.jpg', upload_to='articles'),
        ),
        migrations.AlterField(
            model_name='events',
            name='image2',
            field=models.ImageField(default='eventdefault.jpg', upload_to='articles'),
        ),
        migrations.AlterField(
            model_name='events',
            name='image3',
            field=models.ImageField(default='eventdefault.jpg', upload_to='articles'),
        ),
        migrations.AlterField(
            model_name='events',
            name='image4',
            field=models.ImageField(default='eventdefault.jpg', upload_to='articles'),
        ),
        migrations.AlterField(
            model_name='events',
            name='image5',
            field=models.ImageField(default='eventdefault.jpg', upload_to='articles'),
        ),
    ]
